# Production Configuration with MySQL - for demo purpose only
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:tekmetric_db}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:tekmetric_user}
    password: ${DB_PASSWORD:tekmetric_password}  # Fallback for local testing
    driver-class-name: com.mysql.cj.jdbc.Driver

    # HikariCP connection pool settings for production
    hikari:
      maximum-pool-size: 20           # Handle more concurrent requests (default: 10)
      minimum-idle: 5                 # Save resources when idle (default: same as max)
      idle-timeout: 300000            # Close unused connections after 5min (default: 10min)
      max-lifetime: 600000            # Refresh connections every 10min to prevent stale connections (default: 30min)
      connection-timeout: 20000       # Fail faster on DB issues (default: 30s)
      validation-timeout: 5000        # Connection validation timeout (default: 5s)
      leak-detection-threshold: 60000 # Log connection leaks after 1min (default: disabled)

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true

  # Flyway Configuration for MySQL
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:tekmetric_db}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    user: ${DB_USERNAME:tekmetric_user}
    password: ${DB_PASSWORD:tekmetric_password}  # Fallback for local testing

  jackson:
    deserialization:
      fail-on-unknown-properties: true

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET:change-this-in-production-to-a-secure-secret-key}  # Fallback for local testing
    expiration: 86400000 # 24 hours

# Actuator Configuration (Restricted for Production)
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
  info:
    env:
      enabled: true
    java:
      enabled: false  # Don't expose Java details in production
    os:
      enabled: false  # Don't expose OS details in production

# Logging Configuration
logging:
  level:
    com.interview: INFO
    org.springframework: WARN
    org.hibernate: WARN
    com.zaxxer.hikari: WARN

# Server Configuration
server:
  port: 8080
  compression:
    enabled: true # Compress JSON/text responses (60-80% size reduction)
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  http2:
    enabled: true # Enable HTTP/2 for better concurrent request performance